### ISSUE TITLE
General titleage

### ISSUE THREAD

**Issue by eelegiap** [eelegiap/cs271project#9]
I think we definitely need informative/explanatory titles on all the graphs we include on the analysis panel, since it's not immediately clear what something like the frequency timeline is showing. I can start brainstorming these, and we can also ask Pavan and Raj. 

(In an ideal universe, it would be cool to have a "help" mode, where when it's turned on, you can hover over different elements for fuller explanations of their functionality.)

**Comment by fihenry** [comment]
Resolved by titles and also the descriptions we are going to add
